services:
  api1:
    image: jrblatt/rinha-de-backend-2025-nodejs:1
    container_name: api1
    hostname: api1
    environment:
      - MODE=🔥
      - WORKERS=1
      - EXTERNAL_SUMMARY_HOSTNAME=api2
    volumes:
      - rb2025:/tmp/
    networks:
      - payment-processor
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: 155MB

  api2:
    image: jrblatt/rinha-de-backend-2025-nodejs:1
    container_name: api2
    hostname: api2
    environment:
      - MODE=🔥
      - WORKERS=1
      - EXTERNAL_SUMMARY_HOSTNAME=api1
    volumes:
      - rb2025:/tmp/
    networks:
      - payment-processor
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: 155MB

  nginx:
    image: openresty/openresty:bullseye
    container_name: nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - rb2025:/tmp/
    depends_on:
      - api1
      - api2
    networks:
      - payment-processor
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 40MB

volumes:
  rb2025:
    driver: local

networks:
  payment-processor:
    external: true
    driver: bridge
